dependencies = [
    "from pathlib import Path",
]

codedTokens = {
    "_BASE_DIR": "Path(__file__).resolve().parent",
}

tokens = {
    "DISCORD_TOKEN": "{Put your Discord token here}",
}

from pathlib import Path

_BASE_DIR = Path(__file__).resolve().parent
settingsFile = _BASE_DIR / "settings.py"

RECREATE_SETTINGS_FILE = True

if not settingsFile.is_file() or RECREATE_SETTINGS_FILE:
    settingsFile.touch(exist_ok=True)
    with settingsFile.open("w") as f:
        f.write("# Settings.py\n")
        f.write("# This file is automatically generated.\n")
        f.write("# Please ensure all values are accurate.\n\n")
        for dependency in dependencies:
            f.write(f"{dependency}\n")
        for token in codedTokens:
            f.write(f"{token} = {codedTokens[token]}\n")
        for token in tokens:
            f.write(f'{token} = "{tokens[token]}"\n')
